language: python
install: "pip install -r requirements.txt"
script: nosetests --with-coverage -cover-package=big_data_orm/big_query_connector --cover-package=big_data_orm/resources --cover-html --cover-erase
